# Generated by Django 2.1.3 on 2018-11-06 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(choices=[('4', 'Amarillo'), ('1', 'Negro'), ('2', 'Rojo'), ('3', 'Azul'), ('0', 'Blanco')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='deposito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Deposito'),
        ),
    ]
