# Generated by Django 2.1.3 on 2018-11-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20181107_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('codigo_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Director')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='codigo_profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='codigo_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Clase'),
        ),
    ]
