# Generated by Django 2.1.3 on 2018-11-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20181111_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Maestro',
        ),
    ]
