# Generated by Django 2.1.3 on 2018-11-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20181113_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='password',
            new_name='contrasenia',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='password',
            new_name='contrasenia',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='password',
            new_name='contrasenia',
        ),
        migrations.RenameField(
            model_name='maestro',
            old_name='password',
            new_name='contrasenia',
        ),
    ]
