# Generated by Django 2.1.3 on 2018-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20181113_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='codigo_director',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
