# Generated by Django 2.1.3 on 2018-11-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20181113_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='codigo_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.Director'),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='correo',
            field=models.CharField(max_length=50),
        ),
    ]
