# Generated by Django 2.1.3 on 2018-11-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20181113_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='director',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='maestro',
            name='contrasenia',
        ),
    ]
